NAME_INPUT = "//input[@name='name']"
EMAIL_INPUT = "//input[@name='email']"
PASSWORD_INPUT = "//input[@name='Пароль']"
REGISTER_BUTTON = "//button[text()='Зарегистрироваться']"
LOGIN_BUTTON_MAIN_PAGE = "//button[text()='Войти в аккаунт']"
LOGIN_BUTTON_AUTH = "//button[text()='Войти']"
PERSONAL_ACCOUNT_BUTTON = "//a[@href='/account']"
LOGIN_BUTTON_FORGOT_PASSWORD = "//a[text()='Войти']"
BUNS_SECTION = "//h2[text()='Булки']"
ACTIVE_BUNS_SECTION = "//span[text()='Булки']/parent::div"
SAUCES_SECTION = "//span[text()='Соусы']"
ACTIVE_SAUCES_SECTION = "//span[text()='Соусы']/parent::div"
FILLINGS_SECTION = "//span[text()='Начинки']"
ACTIVE_FILLINGS_SECTION = "//span[text()='Начинки']/parent::div"
ERROR_MESSAGE = "//p[contains(text(), 'Некорректный пароль')]"
LOGOUT_BUTTON = "//button[text()='Выход']"